stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/city_aqi.csv
    outs:
    - data/raw/city_aqi.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/city_aqi.csv
    outs:
    - data/processed/train_city_aqi.csv
    - data/processed/test_city_aqi.csv 

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_city_aqi.csv
    - data/processed/test_city_aqi.csv
    - src/train_and_evaluate.py
    params:
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio
    metrics:
    - reports/scores.json:
        cache: false
    - reports/params.json:
        cache: false
    outs:
    - saved_models/model.joblib
